source "https://supermarket.chef.io"

cookbook "apt"
cookbook "vim"
cookbook "apache2"
cookbook "mysql", "~> 6.0"
cookbook "mysql2_chef_gem", "~> 1.0.1"
cookbook "database", "~> 4.0.3"
cookbook "php", :git => "https://github.com/priestjim/chef-php"
cookbook "xdebug", :git => "https://github.com/escapestudios-cookbooks/xdebug"
cookbook "base", :path => "chef/cookbooks/base"
cookbook "magento-dev", :path => "chef/cookbooks/magento-dev"
