default['app']['app_name'] = 'magento'
default['app']['server_name'] = 'magento.dev'
default['app']['docroot'] = '/var/www/magento'
default['app']['db_name'] = 'magento'
default['app']['db_user'] = 'magento'
default['app']['db_pass'] = 'magento'